### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by kavita-gsphk** [convegenius-tech/facial-recognition-attendance#6]
# Weekly Goals 
## Week 1 
- [ ] Finalise the dataset
- [ ] Steup and understand the working of deepface 

## Week 2
- [ ] Prepare the dataset
- [ ] Create the pipeline for testing with the finalised dataset
- [ ] Finalise and test the top 10 configuration 

## Week 3
- [ ] Test the top 5 configurations with and without the specs dataset
- [ ] Test how models perform with 1. Different image quality 2. Rotated images 3. Blurriness 4. Different resolution

**Comment by gupta-tilak** [comment]
# Weekly Learnings & Updates
## Week 1, 2 and 3
- Finalised Indian-Facial-Database-Highlighting-Spectacle-Problem dataset for the project.
- Understood the working of deepface and studied the preprocessing pipeline which includes normalisation, resizing and alignment.
- Studied various research papers on Facial Recognition and performance of various existing open-source models for the task.
- Preprocessed and cleaned the dataset as per the project requirements keeping 30 images of each individual.
- Prepared 5000 testing combinations with 1500 test images.
- Created the testing pipeline for deepface with 12 initial model-detector-distance-alignment configurations.
- Finalised the top 5 configurations in terms of accuracy and time taken to process the results.
- Built the data augmentation pipeline to test the selected configurations on params like varying image quality, providing a rotation angle to the images, introducing some blurriness in the images and trying out different resolutions.
